# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - master

resources:
  - repo: self

variables:
  tag: '$(Build.BuildId)'
  imageRepository: 'pocnetcore'
  dockerFilePath: '**/Dockerfile'
  vmImageName: 'ubuntu-latest'

pool:
  vmImage: $(vmImageName)

stages:
  - stage: Check
    displayName: Check Stage
    pool:
      vmImage: 'windows-latest'
    jobs:
      - job: Check
        displayName: Sonar Check
        steps:
          - task: SonarCloudPrepare@1
            inputs:
              SonarCloud: 'SonarCloud'
              organization: 'Eldarrin'
              scannerMode: 'MSBuild'
              projectKey: 'Eldarrin_DotnetCoreWebApp'
              projectName: 'DotnetCoreWebApp'
              extraProperties: |
                # Additional properties that will be passed to the scanner,
                # Put one key=value per line, example:
                sonar.organization=eldarrin-github

          - task: MSBuild@1
            inputs:
              solution: '**/*.sln'

          - task: SonarCloudAnalyze@1

          - task: SonarCloudPublish@1
            inputs:
              pollingTimeoutSec: '300'

  - stage: Build
    displayName: Build Stage
    dependsOn: Check
    jobs:
      - job: Build
        displayName: Build
        steps:
          - task: Docker@2
            inputs:
              repository: $(imageRepository)
              command: 'build'
              Dockerfile: '$(dockerfilePath)'
              tags: '$(tag)'
